### ISSUE TITLE
View Work Doesn't work

### ISSUE THREAD

**Issue by Helixable** [BonfireScratch/BonfireScratch.github.io#1]
Hello! Nice job on your website! One small issue: The "View my Work" button does not work on the home page.

**Comment by BonfireScratch** [comment]
@Helixable This is a known issue, as I haven't really had the time to finish my website. It will be done in the near future.

**Comment by Helixable** [comment]
Got it.

**Comment by BonfireScratch** [comment]
@Helixable this will most likely be fixed tomorrow!

**Comment by BonfireScratch** [comment]
@Helixable Done
